name: CI
on: [push, pull_request]

jobs:
  native_build:
    name: Native build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check --all-targets

  web_build:
    name: Web build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: rust-src
      - run: RUSTFLAGS="--cfg=web_sys_unstable_apis" cargo +nightly check -Z build-std=panic_abort,std --target wasm32-unknown-unknown --all-targets

  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
